CREATE TABLE IF NOT EXISTS excursions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titol TEXT NOT NULL,
  descripcio TEXT,
  distancia REAL NOT NULL DEFAULT 0,
  desnivell_pos REAL NOT NULL DEFAULT 0,
  desnivell_neg REAL NOT NULL DEFAULT 0,
  osm INTEGER,
  data_inici TEXT NOT NULL DEFAULT (date('now')),
  data_final TEXT NOT NULL DEFAULT (date('now')),
  slug TEXT UNIQUE NOT NULL,
  privat INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
